[build]
  publish = "dist"
  command = "npm run build"

[[headers]]
  for = "/"
  [headers.values]
    Link = "</sitemap.xml>; rel=\"describedby\"; type=\"application/xml\", </help>; rel=\"service-doc\"; type=\"text/html\""

[[redirects]]
  from = "/api/public-submissions"
  to = "/.netlify/functions/public-submissions"
  status = 200

[[redirects]]
  from = "/api/waitlist"
  to = "/.netlify/functions/waitlist"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
