[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/api/public-submissions"
  to = "/.netlify/functions/public-submissions"
  status = 200

[[redirects]]
  from = "/api/waitlist"
  to = "/.netlify/functions/waitlist"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
