import type { SourcingScenario } from './types';

const observedAt = '20 Aug 2026, 14:20 AEST';
const field = (id: string, label: string, value: string, sourceLabel: string, confidence = 90, editable = true) => {
  const unknown = confidence === 0 || /unknown|not provided|required|unconfirmed/i.test(value);
  return {
    id, label, value,
    source: sourceLabel.includes('Agent') ? 'agent' as const : sourceLabel.includes('Listing') ? 'listing' as const : 'buyer' as const,
    sourceLabel, confidence, observedAt,
    status: unknown ? 'unknown' as const : sourceLabel.includes('Agent') ? 'agent_confirmed' as const : 'extracted' as const,
    editable,
  };
};

const base: SourcingScenario = {
  id: 'wholesale', label: 'Simple wholesale order', shortLabel: 'Wholesale', category: 'Electronics',
  prompt: 'I need 1,000 braided USB C charging cables from this 1688 listing, delivered to Lagos.',
  assistantSummary: 'I translated the submitted listing and prepared a buying brief. The advertised price is not a landed cost, and the supplier identity still needs a verified agent check.',
  brief: [field('product', 'Product', 'Braided USB C to USB C charging cable', 'Buyer request', 100), field('quantity', 'Quantity', '1,000 pieces', 'Buyer request', 100), field('target', 'Target unit cost', 'Not provided', 'Buyer request', 0), field('destination', 'Destination', 'Lagos, Nigeria', 'Buyer request', 100), field('packaging', 'Packaging', 'Individual retail box', 'Listing screenshot', 78)],
  listing: [field('access', 'Listing status', 'Accessible from submitted evidence', 'Listing URL', 100, false), field('title', 'Translated title', '100W nylon braided fast charging cable', 'Listing screenshot', 96), field('moq', 'Advertised MOQ', '100 pieces', 'Listing screenshot', 93), field('price', 'Advertised range', '¥5.20–¥7.80', 'Listing screenshot', 91), field('custom', 'Customization claim', 'Logo and packaging available', 'Listing screenshot', 76), field('badge', 'Platform badge', 'Store badge shown; not Naitrust verification', 'Listing screenshot', 83, false)],
  supplier: [field('supplier', 'Store name', 'Shenzhen Lianhe Digital Store', 'Listing screenshot', 88), field('city', 'Claimed location', 'Shenzhen, Guangdong', 'Listing screenshot', 84), field('legal', 'Legal entity', 'Unknown, agent document check required', 'Agent pending', 0, false), field('factory', 'Factory status', 'Unconfirmed', 'Agent pending', 0, false), field('beneficiary', 'Payment beneficiary', 'Must match approved supplier evidence', 'Naitrust policy', 100, false)],
  quotes: [{ id: 'q1', supplier: 'Shenzhen Lianhe Digital', unitPrice: '¥6.40', moq: '1,000', leadTime: '18 days', incoterm: 'EXW Shenzhen', paymentTerms: '30% / 70%', status: 'recommended', flags: ['Freight excluded', 'Confirm 100W test report'] }, { id: 'q2', supplier: 'Dongguan PowerLink', unitPrice: '¥5.95', moq: '2,000', leadTime: '25 days', incoterm: 'FOB Shenzhen', paymentTerms: '50% / 50%', status: 'needs_clarification', flags: ['MOQ exceeds request', 'Packaging price missing'] }],
  agents: [{ id: 'a1', name: 'Amina Yusuf', city: 'Shenzhen', rating: 4.8, completedTasks: 44, response: 'Usually 24 minutes · SLA 12 hours', matchReasons: ['Based in Shenzhen', 'Electronics batch testing', 'Mandarin and English'], status: 'recommended' }, { id: 'a2', name: 'Chinedu Okafor', businessName: 'Okafor China Sourcing Ltd', city: 'Guangzhou', rating: 4.9, completedTasks: 61, response: 'Usually 18 minutes · SLA 12 hours', matchReasons: ['Covers Shenzhen', 'Supplier negotiation', 'Warehouse consolidation'], status: 'assigned' }],
  inspection: [{ id: 'i1', label: 'Confirm cable length and connector finish', evidence: 'Measurement photos and sample video', status: 'pending' }, { id: 'i2', label: 'Test charging output across random sample', evidence: 'Test meter video for 30 units', status: 'pending' }, { id: 'i3', label: 'Confirm logo, barcode and retail box', evidence: 'Approved sample against production units', status: 'human_review' }],
  payments: [{ id: 'p1', label: 'Agent investigation fee', percentage: 5, beneficiary: 'Verified sourcing agent', evidence: 'Accepted assignment', status: 'buyer_review' }, { id: 'p2', label: 'Supplier deposit', percentage: 30, beneficiary: 'Approved supplier account', evidence: 'Entity and sample confirmation', status: 'locked' }, { id: 'p3', label: 'Production balance', percentage: 65, beneficiary: 'Approved supplier account', evidence: 'Passed final inspection and pickup readiness', status: 'locked' }],
  logistics: [{ id: 'l1', provider: 'JadeBridge Cargo', mode: 'Sea', price: '₦1,280,000 estimate', eta: '34 to 42 days', includes: ['China pickup', 'Sea freight', 'Lagos clearing'], excludes: ['Cargo insurance', 'Final mile delivery'], status: 'recommended' }, { id: 'l2', provider: 'SkyRoute Express', mode: 'Air', price: '₦3,640,000 estimate', eta: '8 to 12 days', includes: ['China pickup', 'Air freight', 'Lagos clearing', 'Final mile'], excludes: ['Insurance above basic cover'], status: 'available' }],
  bilingualDraft: { approved: false, english: 'Please confirm the price for 1,000 units, 100W charging support, individual retail boxes, logo printing, production lead time and sample availability. Please include the legal company name and beneficiary account on the quotation.', chinese: '请确认1000件产品的价格、100W快充支持、独立零售包装、Logo印刷、生产周期和样品安排。请在报价单中注明公司法定名称和收款账户。' },
};

const clone = (changes: Partial<SourcingScenario>): SourcingScenario => ({ ...base, ...changes });

export const sourcingScenarios: SourcingScenario[] = [
  base,
  clone({ id: 'custom', label: 'Custom manufacturing', shortLabel: 'Custom product', category: 'Fashion & footwear', prompt: 'Manufacture 600 private label sneakers using my logo and custom boxes.', assistantSummary: 'This is a custom production request. A pre production sample, material specification and size breakdown must be approved before a supplier deposit.', brief: [field('product', 'Product', 'Private label casual sneakers', 'Buyer request', 100), field('quantity', 'Quantity', '600 pairs', 'Buyer request', 100), field('sizes', 'Size range', 'EU 36 to 46; breakdown missing', 'Buyer request', 72), field('material', 'Upper material', 'Buyer confirmation required', 'Buyer request', 0), field('branding', 'Branding', 'Black woven logo and custom box', 'Buyer request', 96)] }),
  clone({ id: 'blocked', label: 'Inaccessible 1688 listing', shortLabel: 'Blocked link', category: 'General wholesale', prompt: 'Can you check this 1688 link? It requires login.', assistantSummary: 'I could not access listing evidence from the URL. I have not inferred the product, supplier, price or platform badges. Upload screenshots or ask an assigned agent to capture the listing.', notice: { tone: 'warning', title: 'Listing evidence unavailable', body: 'Naitrust does not bypass marketplace logins or CAPTCHAs. Unknown fields remain unknown.' }, listing: [field('access', 'Listing status', 'Login required, screenshots requested', 'Submitted URL', 100, false), field('title', 'Product title', 'Unknown', 'No evidence', 0), field('price', 'Advertised price', 'Unknown', 'No evidence', 0), field('supplier', 'Supplier/store', 'Unknown', 'No evidence', 0)] }),
  clone({ id: 'conflict', label: 'Conflicting quotations', shortLabel: 'Quote conflict', category: 'Printing & packaging', prompt: 'Compare these two box quotations. One supplier changed the price.', assistantSummary: 'The quotations use different quantities and Incoterms, so their unit prices are not directly comparable. Supplier A also changed its beneficiary details and requires operations review.', notice: { tone: 'danger', title: 'Beneficiary change detected', body: 'No payment can proceed until the verified agent and Naitrust operations confirm the new beneficiary.' }, quotes: [{ id: 'q1', supplier: 'Foshan PackPro', unitPrice: '¥2.85 → ¥3.30', moq: '5,000', leadTime: '16 days', incoterm: 'EXW', paymentTerms: '50% / 50%', status: 'conflict', flags: ['Price changed after approval', 'Beneficiary changed'] }, { id: 'q2', supplier: 'Guangzhou BoxLab', unitPrice: '¥3.45', moq: '3,000', leadTime: '14 days', incoterm: 'FOB', paymentTerms: '30% / 70%', status: 'complete', flags: ['Tooling charged separately'] }] }),
  clone({ id: 'restricted', label: 'Restricted product', shortLabel: 'Restricted', category: 'Controlled goods', prompt: 'I want to import a large order of medical diagnostic devices.', assistantSummary: 'This request may require Nigerian regulatory permits and product documentation. AI analysis is paused until Naitrust operations reviews the category.', notice: { tone: 'danger', title: 'Manual compliance review required', body: 'No supplier engagement, order conversion or payment action is available for this request yet.' } }),
  clone({ id: 'delayed', label: 'Delayed sourcing agent', shortLabel: 'Agent overdue', category: 'Furniture & interiors', prompt: 'My assigned agent has not updated the factory visit.', assistantSummary: 'The 12 hour acknowledgement window has passed. I prepared a reminder and recommend operations review or reassignment; it will not be sent without approval.', notice: { tone: 'warning', title: 'Agent response overdue', body: 'Response score impact is simulated. The buyer may approve a reminder or request reassignment.' }, agents: [{ ...base.agents[0], city: 'Foshan', status: 'overdue', response: '14h 18m without update · SLA breached' }, base.agents[1]] }),
  clone({ id: 'inspection', label: 'Failed inspection', shortLabel: 'Failed inspection', category: 'Electronics', prompt: 'The agent says part of the cable batch failed testing.', assistantSummary: 'The submitted evidence shows an 11% random sample failure rate. I recommend freezing the production balance and requesting rework plus a new inspection.', notice: { tone: 'danger', title: 'Release not recommended', body: 'AI cannot freeze or release funds. Buyer and operations approval are required.' }, inspection: [{ ...base.inspection[0], status: 'passed' }, { ...base.inspection[1], evidence: '11 of 100 sampled units failed output test', status: 'failed' }, { ...base.inspection[2], status: 'passed' }], payments: base.payments.map((stage, index) => index === 2 ? { ...stage, status: 'disputed' as const } : stage) }),
  clone({ id: 'shipment', label: 'Shipment exception', shortLabel: 'Shipment issue', category: 'General wholesale', prompt: 'The sea shipment has a customs documentation issue in Lagos.', assistantSummary: 'The clearing partner reported a mismatch between the packing list and shipment quantity. Final delivery is paused while the agent and logistics provider reconcile documents.', notice: { tone: 'warning', title: 'Customs exception', body: 'Estimated delivery is suspended until the corrected packing list is accepted.' }, logistics: [{ ...base.logistics[0], status: 'exception', eta: 'Paused, customs review' }, base.logistics[1]] }),
];

export const defaultRunSteps = ['Understanding your request', 'Reading the image, link or voice note', 'Searching for matching products', 'Translating product information', 'Comparing products and sellers'];
