import { ChevronDown, Clock3, Loader2, RefreshCw, Sparkles } from 'lucide-react';
import type { ExtendedProductTestingDays } from '../../../libs/store/types';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '../../ui/collapsible';
import { Input } from '../../ui/input';
import { Label } from '../../ui/label';
import { Textarea } from '../../ui/textarea';
import { Badge } from '../../ui/badge';
import { Button } from '../../ui/button';

interface PaymentConditionsStepProps {
  splitPayment: boolean;
  useCase: string;
  releaseConditions: string;
  nextPaymentReleaseConditions: string;
  extendedProductTestingDays?: ExtendedProductTestingDays;
  openUntil: string;
  minOpen: string;
  maxOpen: string;
  maxOpenDays: number;
  showAdvancedTiming: boolean;
  errors: Record<string, string>;
  generatedByAi: boolean;
  generating: boolean;
  onGenerate: () => void;
  onFieldChange: (field: 'releaseConditions' | 'nextPaymentReleaseConditions' | 'openUntil', value: string) => void;
  onTestingPeriodChange: (value?: ExtendedProductTestingDays) => void;
  onAdvancedTimingChange: (open: boolean) => void;
}

function FieldError({ message }: { message?: string }) {
  return message ? <p className="mt-1 text-xs text-destructive">{message}</p> : null;
}

export function PaymentConditionsStep(props: PaymentConditionsStepProps) {
  return (
    <div className="space-y-5">
      <div>
        <p className="text-sm font-bold text-foreground">Payment conditions</p>
        <p className="mt-1 text-xs leading-5 text-muted-foreground">
          {props.splitPayment ? 'Set what releases the first payment and what must happen before the remaining payment is available.' : 'Set what must happen before this payment can be released.'}
        </p>
      </div>
      <div>
        <div className="flex flex-wrap items-center justify-between gap-2">
          <Label htmlFor="release">{props.splitPayment ? 'First payment release condition' : 'Payment conditions write up'}</Label>
          <Button type="button" size="sm" variant="outline" className="h-8 rounded-full" onClick={props.onGenerate} disabled={props.generating}>
            {props.generating ? <Loader2 size={13} className="mr-1.5 animate-spin" /> : props.generatedByAi ? <RefreshCw size={13} className="mr-1.5" /> : <Sparkles size={13} className="mr-1.5 text-primary" />}
            {props.generatedByAi ? 'Get another draft' : 'Generate with AI'}
          </Button>
        </div>
        {props.generatedByAi && <div className="mt-2 flex items-start gap-2 rounded-xl border border-primary/15 bg-primary/[0.04] px-3 py-2"><Badge variant="outline" className="mt-0.5 shrink-0 gap-1"><Sparkles size={11} />Generated by AI</Badge><p className="text-xs leading-5 text-muted-foreground">Drafted from this deal’s details. Read and edit it to make sure it meets your expectations; the other party must review it too.</p></div>}
        <Textarea id="release" className="mt-2" rows={props.generatedByAi ? 15 : 6} value={props.releaseConditions} onChange={(event) => props.onFieldChange('releaseConditions', event.target.value)} />
        <p className="mt-1.5 text-xs leading-5 text-muted-foreground">After the 10-minute handover check, a 1-hour review applies before payment releases automatically. The buyer may approve an earlier release with their transaction PIN after a final warning.</p>
        <FieldError message={props.errors.releaseConditions} />
      </div>
      {props.splitPayment && <div><Label htmlFor="next-payment-condition">Second payment release condition</Label><Textarea id="next-payment-condition" className="mt-1.5" rows={3} placeholder="For example: Release the remaining payment after final delivery is inspected and accepted." value={props.nextPaymentReleaseConditions} onChange={(event) => props.onFieldChange('nextPaymentReleaseConditions', event.target.value)} /><p className="mt-1 text-xs leading-5 text-muted-foreground">The second payment stays locked until the first payment is released successfully. Once its condition is confirmed, it receives its own 1-hour review period.</p><FieldError message={props.errors.nextPaymentReleaseConditions} /></div>}
      <Collapsible open={props.showAdvancedTiming} onOpenChange={props.onAdvancedTimingChange} className="rounded-2xl border">
        <CollapsibleTrigger className="flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left"><span className="flex items-center gap-2 text-sm font-semibold"><Clock3 size={15} className="text-primary" />Invitation timing</span><span className="flex items-center gap-2 text-xs text-muted-foreground">Expires after 7 days by default<ChevronDown size={15} className={`transition-transform ${props.showAdvancedTiming ? 'rotate-180' : ''}`} /></span></CollapsibleTrigger>
        <CollapsibleContent className="border-t px-4 py-4"><Label htmlFor="open">Invitation expires</Label><Input id="open" type="date" min={props.minOpen} max={props.maxOpen} className="mt-1.5 max-w-sm" value={props.openUntil} onChange={(event) => props.onFieldChange('openUntil', event.target.value)} /><p className="mt-1 text-xs leading-5 text-muted-foreground">The other party must accept before this date. You can choose up to {props.maxOpenDays} days.</p><FieldError message={props.errors.openUntil} /></CollapsibleContent>
      </Collapsible>
    </div>
  );
}
