import { serviceInformation } from '../../content/service-information';
import { ArrowRight, FileText, Fingerprint, HeartHandshake } from 'lucide-react';
import { SEOHead } from '../utility/SEOHead';
import { pageImages } from '../../libs/images/image-manifest';

export function AboutPage({ onNavigate }: { onNavigate: (page: string, params?: unknown) => void }) {
  return <div className="nt-marketing">
    <SEOHead title="A little more trust in every deal" description="Meet Naitrust: we are building secure payments for buyers and sellers in Nigeria, with clear agreements, shared evidence and controlled release." canonicalPath="/about" />
    <section className="nt-about-hero nt-container"><p className="nt-eyebrow">WHY WE’RE BUILDING NAITRUST</p><h1>Good people.<br />Great possibilities.<br /><span>Better ways to trust.</span></h1><p>Buying and selling should bring people together.<br className="nt-desktop-break" /> We’re here to make the payment part feel a little clearer.</p><img src={pageImages.aboutHero.src} alt={pageImages.aboutHero.alt} fetchPriority="high" /></section>
    <section className="nt-container nt-about-story"><div><p className="nt-eyebrow">THE IDEA IS SIMPLE</p><h2>Less “what if?”<br />More moving forward.</h2></div><div><p>You’ve found the right product. Or someone who can do the job. But before money changes hands, there’s a question: how do we make this work for both of us?</p><p>Naitrust is being built to help buyers and sellers answer that together. Clear terms. Participant checks. A shared record. Payment release connected to the agreement.</p><p>We bring the transaction together in a Protected Deal, so both sides can see what was promised, what has happened and what comes next.</p></div></section>
    <section className="nt-about-values"><div className="nt-container"><p className="nt-eyebrow">WHAT MATTERS TO US</p><h2>Trust, with something<br />to stand on.</h2><div className="nt-usecase-grid">{[{icon:Fingerprint,title:'Know who’s involved.',text:'Specific identity and business checks give people clearer information about the other party.'},{icon:FileText,title:'Make the details clear.',text:'Keep terms, evidence and payment decisions in the same place, where both sides can follow them.'},{icon:HeartHandshake,title:'Think about both sides.',text:'Buyers need confidence in the outcome. Sellers need a clear path to payment. Both deserve to be heard.'}].map(({icon:Icon,title,text})=><article key={title}><Icon size={30} strokeWidth={1.5}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="nt-container nt-about-story"><div><p className="nt-eyebrow">BUILT FOR BOTH SIDES</p><h2>Know what’s agreed.<br />See what happens next.</h2></div><div><p>From an online purchase to a service contract, both sides deserve clear terms and a payment process they can follow.</p><p>A Protected Deal keeps the agreement, messages and evidence together, so you have a shared record if questions arise.</p><p>Operated by {serviceInformation.company} for buyers and sellers in Nigeria.</p><button className="nt-text-link" onClick={() => onNavigate('compliance')}>Our approach to trust <ArrowRight size={18}/></button></div></section>
    <section className="nt-container nt-final-wrap"><div className="nt-final-cta"><p className="nt-eyebrow">BE PART OF WHAT COMES NEXT</p><h2>Let’s make good deals happen.</h2><button className="nt-button nt-button-white" onClick={() => onNavigate('/waitlist')}>Join early access <ArrowRight size={18} /></button></div></section>
  </div>;
}
