import { useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, FileCheck2, MessageCircle, Paperclip, Send, ShieldCheck, Video } from 'lucide-react';
import { toast } from 'sonner';
import { DashboardLayout } from '../pieces/dashboard/DashboardLayout';
import { PinPromptModal } from '../pieces/security/PinPromptModal';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Card } from '../ui/card';
import { Input } from '../ui/input';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '../ui/tabs';
import { Textarea } from '../ui/textarea';
import { sourcingApi } from '../../features/sourcing/api/sourcing.api';
import { OperationsHeader } from '../../features/sourcing/components/OperationsHeader';
import { useOperationsRefresh } from '../../features/sourcing/hooks/use-operations-refresh';

export function AgentAssignmentPage() {
  useOperationsRefresh();
  const navigate = useNavigate();
  const { assignmentId } = useParams<{ assignmentId?: string }>();
  const assignments = sourcingApi.listAssignments();
  const assignment = assignmentId ? sourcingApi.getAssignment(assignmentId) : undefined;
  const [message, setMessage] = useState('');
  const [evidenceTitle, setEvidenceTitle] = useState('');
  const [evidenceDescription, setEvidenceDescription] = useState('');
  const [pendingCertification, setPendingCertification] = useState<string | null>(null);

  if (!assignmentId) return <DashboardLayout title="Agent assignments"><div className="mx-auto w-full max-w-6xl space-y-5"><OperationsHeader eyebrow="Sourcing work" title="Your agent assignments" description="Keep supplier checks, bargaining, product evidence, readiness recommendations and decisions attached to the correct order." icon={FileCheck2} badge={`${assignments.length} assignments`} /><div className="grid gap-4 md:grid-cols-2">{assignments.map((item) => { const agent = sourcingApi.listAgents().find((candidate) => candidate.id === item.agentId); return <button key={item.id} type="button" onClick={() => navigate(`/app/agent-assignments/${item.id}`)} className="rounded-3xl border bg-card p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-start justify-between gap-3"><Badge className="capitalize">{item.status.replace(/_/g, ' ')}</Badge><span className="text-[10px] text-muted-foreground">Due {new Date(item.deadline).toLocaleDateString()}</span></div><h2 className="mt-4 font-bold">{item.title}</h2><p className="mt-1 text-xs text-muted-foreground">{agent?.name} · {item.supplierCity}, China</p><div className="mt-4 flex gap-3 text-[11px] text-muted-foreground"><span>{item.productScopes.length} product scope</span><span>{item.evidence.length} evidence files</span><span>{item.messages.length} messages</span></div></button>; })}{assignments.length === 0 && <Card className="col-span-full rounded-3xl border-dashed p-12 text-center"><FileCheck2 className="mx-auto text-muted-foreground" /><h2 className="mt-4 font-bold">No assignments yet</h2><p className="mt-2 text-sm text-muted-foreground">Choose an agent from the sourcing-agent directory.</p><Button className="mt-5 rounded-full" onClick={() => navigate('/app/agents')}>Find an agent</Button></Card>}</div></div></DashboardLayout>;
  if (!assignment) return <DashboardLayout title="Agent assignment"><Card className="mx-auto max-w-xl rounded-3xl p-10 text-center"><h1 className="font-bold">Assignment not found</h1><Button className="mt-5 rounded-full" onClick={() => navigate('/app/agent-assignments')}>Back to assignments</Button></Card></DashboardLayout>;

  const agent = sourcingApi.listAgents().find((candidate) => candidate.id === assignment.agentId);
  const submitMessage = () => { if (!message.trim()) return; const result = sourcingApi.sendMessage(assignment.id, message); setMessage(''); toast[result.flagged ? 'warning' : 'success'](result.flagged ? 'Contact details were removed. Keep communication inside Naitrust.' : 'Message sent.'); };
  const addEvidence = () => { if (!evidenceTitle.trim() || !assignment.productScopes[0]) { toast.error('Add an evidence title.'); return; } sourcingApi.addMockEvidence(assignment.id, { productScopeId: assignment.productScopes[0].id, kind: 'document', title: evidenceTitle, description: evidenceDescription || 'Evidence added to this assignment.', fileName: `${evidenceTitle.toLowerCase().replace(/[^a-z0-9]+/g, '-')}.pdf` }); setEvidenceTitle(''); setEvidenceDescription(''); toast.success('Mock evidence added.'); };
  const approve = () => { if (!pendingCertification) return; sourcingApi.reviewCertification(assignment.id, pendingCertification, 'approve'); setPendingCertification(null); toast.success('Milestone approved. The payment partner can now process settlement.'); };

  return <DashboardLayout title="Agent assignment"><div className="mx-auto w-full max-w-6xl space-y-4">
    <Button variant="ghost" className="-ml-2 rounded-full" onClick={() => navigate('/app/agent-assignments')}><ArrowLeft size={15} /> Assignments</Button>
    <OperationsHeader eyebrow="Agent room" title={assignment.title} description={`${agent?.name ?? 'Assigned agent'} is working with ${assignment.supplierName} in ${assignment.supplierCity}. Every product check, message, evidence file and payment recommendation stays here.`} icon={ShieldCheck} badge={assignment.status.replace(/_/g, ' ')} />
    <Tabs defaultValue="overview"><TabsList className="grid h-11 w-full grid-cols-4 rounded-2xl bg-muted p-1"><TabsTrigger value="overview" className="rounded-xl">Overview</TabsTrigger><TabsTrigger value="messages" className="rounded-xl">Messages</TabsTrigger><TabsTrigger value="evidence" className="rounded-xl">Evidence</TabsTrigger><TabsTrigger value="payments" className="rounded-xl">Payments</TabsTrigger></TabsList>
      <TabsContent value="overview" className="mt-4"><div className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><Card className="rounded-3xl p-5 sm:p-6"><h2 className="font-bold">Product checks</h2><div className="mt-4 space-y-3">{assignment.productScopes.map((scope) => <div key={scope.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><p className="font-semibold">{scope.productName}</p><Badge variant={scope.status === 'passed' ? 'success' : 'outline'} className="capitalize">{scope.status.replace(/_/g, ' ')}</Badge></div><ul className="mt-3 space-y-1 text-xs text-muted-foreground">{scope.requirements.map((item) => <li key={item}>• {item}</li>)}</ul></div>)}</div></Card><Card className="rounded-3xl p-5"><h2 className="font-bold">Assignment details</h2><dl className="mt-4 space-y-3 text-sm"><div><dt className="text-xs text-muted-foreground">Agent</dt><dd className="mt-1 font-medium">{agent?.name}</dd></div><div><dt className="text-xs text-muted-foreground">Supplier</dt><dd className="mt-1 font-medium">{assignment.supplierName}</dd></div><div><dt className="text-xs text-muted-foreground">Deadline</dt><dd className="mt-1 font-medium">{new Date(assignment.deadline).toLocaleDateString()}</dd></div><div><dt className="text-xs text-muted-foreground">Scope</dt><dd className="mt-1 leading-6 text-muted-foreground">{assignment.scope}</dd></div></dl></Card></div></TabsContent>
      <TabsContent value="messages" className="mt-4"><Card className="mx-auto max-w-3xl rounded-3xl p-4 sm:p-6"><div className="max-h-[30rem] space-y-3 overflow-y-auto pr-1">{assignment.messages.map((item) => <div key={item.id} className={`max-w-[88%] rounded-2xl p-3 ${item.senderRole === 'buyer' ? 'ml-auto bg-primary text-primary-foreground' : 'bg-muted'}`}><p className="text-[10px] font-semibold opacity-70">{item.senderName}</p><p className="mt-1 text-sm leading-6">{item.body}</p><p className="mt-1 text-[9px] opacity-60">{new Date(item.createdAt).toLocaleString()}</p></div>)}</div><div className="mt-4 flex items-end gap-2 border-t pt-4"><Textarea value={message} onChange={(event) => setMessage(event.target.value)} className="min-h-11 flex-1 resize-none" placeholder="Message the assigned agent" /><Button size="icon" className="h-11 w-11 shrink-0 rounded-full" onClick={submitMessage}><Send size={16} /></Button></div><p className="mt-2 text-[10px] text-muted-foreground">Phone numbers, email addresses, social handles and external payment links are removed.</p></Card></TabsContent>
      <TabsContent value="evidence" className="mt-4"><div className="grid gap-4 lg:grid-cols-[1fr_.7fr]"><Card className="rounded-3xl p-5"><h2 className="font-bold">Evidence library</h2><div className="mt-4 space-y-3">{assignment.evidence.map((item) => <div key={item.id} className="flex gap-3 rounded-2xl border p-4"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-primary/10 text-primary">{item.kind === 'video' ? <Video size={16} /> : <Paperclip size={16} />}</span><div><p className="text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{item.description}</p><p className="mt-2 text-[10px] text-muted-foreground">{item.submittedBy} · {new Date(item.createdAt).toLocaleString()}</p></div></div>)}{assignment.evidence.length === 0 && <p className="py-8 text-center text-sm text-muted-foreground">No evidence submitted yet.</p>}</div></Card><Card className="h-fit rounded-3xl p-5"><h2 className="font-bold">Add mock evidence</h2><p className="mt-1 text-xs text-muted-foreground">Represents the future signed-upload API without storing binary files in localStorage.</p><Input className="mt-4" value={evidenceTitle} onChange={(event) => setEvidenceTitle(event.target.value)} placeholder="Evidence title" /><Textarea className="mt-3 min-h-24" value={evidenceDescription} onChange={(event) => setEvidenceDescription(event.target.value)} placeholder="What this proves" /><Button className="mt-4 w-full rounded-full" onClick={addEvidence}>Add evidence record</Button></Card></div></TabsContent>
      <TabsContent value="payments" className="mt-4"><div className="space-y-3">{assignment.milestones.map((milestone) => { const certification = assignment.certifications.find((item) => item.milestoneId === milestone.id); return <Card key={milestone.id} className="rounded-3xl p-5 sm:p-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs text-muted-foreground">{milestone.percent}% milestone</p><h2 className="mt-1 font-bold">{milestone.label}</h2></div><Badge variant={milestone.status === 'paid' ? 'success' : 'outline'} className="capitalize">{milestone.status.replace(/_/g, ' ')}</Badge></div><div className="mt-4 flex flex-wrap gap-1.5">{milestone.requiredEvidence.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div>{certification && <div className="mt-4 rounded-2xl bg-primary/[.045] p-4"><p className="flex items-center gap-2 text-sm font-semibold"><CheckCircle2 size={15} className="text-primary" /> Agent readiness certification</p><p className="mt-2 text-xs leading-5 text-muted-foreground">{certification.declaration}</p>{certification.status === 'buyer_review' && <div className="mt-4 flex flex-wrap gap-2"><Button size="sm" className="rounded-full" onClick={() => setPendingCertification(certification.id)}>Approve payment</Button><Button size="sm" variant="outline" className="rounded-full" onClick={() => { sourcingApi.reviewCertification(assignment.id, certification.id, 'changes'); toast.success('Changes requested.'); }}>Request changes</Button><Button size="sm" variant="ghost" className="rounded-full text-destructive" onClick={() => { sourcingApi.reviewCertification(assignment.id, certification.id, 'dispute'); toast.warning('Issue opened and milestone remains unpaid.'); }}>Report issue</Button></div>}</div>}</Card>; })}</div></TabsContent>
    </Tabs>
    <PinPromptModal open={Boolean(pendingCertification)} onOpenChange={(open) => !open && setPendingCertification(null)} onVerified={approve} title="Approve supplier milestone" description="Confirm that you reviewed the agent evidence. The licensed payment partner—not the agent—will process settlement to the verified supplier." />
  </div></DashboardLayout>;
}
