import { ArrowRight, Check, FileText, LockKeyhole, ShieldCheck } from 'lucide-react';
import { SEOHead } from '../utility/SEOHead';
import { pageImages } from '../../libs/images/image-manifest';
import { audienceContent, type Audience } from '../../content/audience-page-content';

export function AudiencePage({ audience, onNavigate }: { audience: Audience; onNavigate: (page: string) => void }) {
  const business = audience === 'business';
  const page = audienceContent.en[audience];
  const join = () => onNavigate('/waitlist');
  return <div className="nt-marketing">
    <SEOHead title={business ? 'A better way to do business' : 'Buy with a little more confidence'} description={page.description} canonicalPath={business ? '/business' : '/customer'} />
    <section className={`nt-subhero ${business ? 'nt-subhero-blue' : 'nt-subhero-peach'}`}><div className="nt-container nt-subhero-grid"><div><p className="nt-eyebrow">{business ? 'NAITRUST FOR BUSINESSES' : 'NAITRUST FOR INDIVIDUALS'}</p><h1>{business ? <>Good business.<br />Clearer payments.</> : <>Go ahead.<br />Make it a<br />good deal.</>}</h1><p>{business ? 'Put your energy into what you do best. Keep customer payments, vendor agreements and the evidence behind them in one shared space.' : 'That new phone. A home repair. Something you’ve saved for. Give your next payment a clear agreement and a little more peace of mind.'}</p><button className="nt-button" onClick={join}>Join early access <ArrowRight size={18} /></button><small>Protected payments for Nigeria. Coming soon.</small></div><div className="nt-subhero-image"><img src={business ? pageImages.businessHero.src : pageImages.customerHero.src} alt={business ? pageImages.businessHero.alt : pageImages.customerHero.alt} fetchPriority="high" /><div className="nt-floating-note"><span className="nt-success-icon"><ShieldCheck size={20} /></span><div><strong>{business ? 'More clarity. Better business.' : 'Your deal. All in one place.'}</strong><small>Built around both sides.</small></div></div></div></div></section>
    <section className="nt-container nt-usecases"><div className="nt-section-heading"><div><p className="nt-eyebrow">MADE FOR YOUR EVERYDAY DEALS</p><h2>{business ? <>For the work.<br />And everything behind it.</> : <>Big plans.<br />Everyday peace of mind.</>}</h2></div><p>{business ? 'One place to agree, document and review.' : 'A clearer way to pay for the things that matter.'}</p></div><div className="nt-usecase-grid">{page.useCases.map(({title,text,icon:Icon},index)=><article key={title}><span className={`nt-usecase-icon nt-tone-${index}`}><Icon size={25} strokeWidth={1.5} /></span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="nt-audience-detail"><div className="nt-container nt-room-section"><div className="nt-section-copy"><p className="nt-eyebrow">KNOW WHERE YOU STAND</p><h2>{business ? <>The agreement.<br />The evidence.<br />The bigger picture.</> : <>Less second guessing.<br />More certainty.</>}</h2><p>{business ? 'Both parties see what was agreed, the funding status and what needs to happen before release. Keep your delivery or service evidence connected to the payment.' : 'See who you’re paying. Record exactly what you expect. Review the outcome and raise a concern through a documented process if something isn’t right.'}</p><ul className="nt-check-list"><li><Check size={18} /> Clear roles and release conditions</li><li><Check size={18} /> Shared messages and supporting files</li><li><Check size={18} /> Evidence to support an informed decision</li></ul><button className="nt-text-link" onClick={() => onNavigate('faqs')}>Get to know Protected Deals <ArrowRight size={18} /></button></div><div className="nt-detail-cards">{[[FileText,'Start with the same agreement.','The amount, deliverables, deadline and release conditions.'],[LockKeyhole,'Know the payment status.','Funding confirmation through an approved payment provider.'],[ShieldCheck,'Make the next step clear.','Review evidence, approve release or report an issue.']].map(([Icon,title,text],index)=>{const ItemIcon=Icon as typeof FileText;return <article key={String(title)}><span>0{index+1}</span><ItemIcon size={25} strokeWidth={1.5}/><h3>{String(title)}</h3><p>{String(text)}</p></article>;})}</div></div></section>
    <section className="nt-container nt-final-wrap nt-audience-final"><div className="nt-final-cta"><p className="nt-eyebrow">LET’S BUILD BETTER DEALS</p><h2>{business ? 'Your next chapter in business.' : 'Your next deal deserves better.'}</h2><button className="nt-button nt-button-white" onClick={join}>Join the waiting list <ArrowRight size={18} /></button><p className="nt-final-note">Join the waiting list for launch updates.</p></div></section>
  </div>;
}
