import { useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { ArrowRight, Boxes, CheckCircle2, MapPin, PackageCheck, Ship, Star, Truck } from 'lucide-react';
import { toast } from 'sonner';
import { DashboardLayout } from '../pieces/dashboard/DashboardLayout';
import { Badge } from '../ui/badge';
import { Button } from '../ui/button';
import { Card } from '../ui/card';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '../ui/dialog';
import { Input } from '../ui/input';
import { sourcingApi } from '../../features/sourcing/api/sourcing.api';
import { OperationsHeader } from '../../features/sourcing/components/OperationsHeader';
import type { ShipmentBatch } from '../../features/sourcing/domain/types';
import { useOperationsRefresh } from '../../features/sourcing/hooks/use-operations-refresh';

const money = (minor: number) => new Intl.NumberFormat('en-NG', { style: 'currency', currency: 'NGN', maximumFractionDigits: 0 }).format(minor / 100);

export function LogisticsPage() {
  useOperationsRefresh();
  const { pathname } = useLocation();
  const navigate = useNavigate();
  const isShipments = pathname.startsWith('/app/shipments');
  const providers = sourcingApi.listLogisticsProviders();
  const shipments = sourcingApi.listShipments();
  const [selected, setSelected] = useState<ShipmentBatch | null>(null);

  if (isShipments) return <DashboardLayout title="Shipments"><div className="mx-auto w-full max-w-6xl space-y-5"><OperationsHeader eyebrow="Flexible consolidation" title="Ship orders when they are ready" description="Wait for every supplier by default, or create a shipment from a ready subset. Product orders and supplier funds remain independent." icon={Ship} badge={`${shipments.length} shipment batches`} /><div className="grid gap-4 md:grid-cols-2">{shipments.map((shipment) => <Card key={shipment.id} className="rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><Badge className="capitalize">{shipment.status.replace(/_/g, ' ')}</Badge><span className="text-[10px] text-muted-foreground">{shipment.reference}</span></div><h2 className="mt-4 font-bold">{shipment.name}</h2><p className="mt-1 flex items-center gap-1 text-xs text-muted-foreground"><MapPin size={12} /> {shipment.destination}</p><div className="mt-4 space-y-2">{shipment.orders.map((order) => <div key={order.orderId} className="flex items-center justify-between rounded-xl bg-muted/55 p-3 text-xs"><span><strong className="block">{order.supplierName}</strong><span className="text-muted-foreground">{order.packageCount} cartons · {order.weightKg} kg</span></span><Badge variant={order.ready ? 'success' : 'outline'}>{order.ready ? 'Ready' : 'Waiting'}</Badge></div>)}</div><Button variant="outline" className="mt-4 w-full rounded-full" onClick={() => setSelected(shipment)}>Review shipping quotes <ArrowRight size={14} /></Button></Card>)}</div><Dialog open={Boolean(selected)} onOpenChange={(open) => !open && setSelected(null)}><DialogContent className="max-h-[92svh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{selected?.name}</DialogTitle><DialogDescription>Compare the services and delivery estimate before booking.</DialogDescription></DialogHeader><div className="space-y-3">{selected?.quotes.map((quote) => { const provider = providers.find((item) => item.id === quote.providerId); return <div key={quote.id} className="rounded-2xl border p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{provider?.name}</p><p className="mt-1 text-xs text-muted-foreground">{quote.mode.toUpperCase()} · about {quote.estimatedDays} days</p></div><p className="font-bold">{money(quote.amountMinor)}</p></div><div className="mt-3 flex flex-wrap gap-1">{quote.includedServices.map((item) => <Badge key={item} variant="secondary">{item}</Badge>)}</div>{quote.status === 'ready' && <Button size="sm" className="mt-4 w-full rounded-full" onClick={() => { sourcingApi.acceptShippingQuote(selected.id, quote.id); toast.success('Shipping quote accepted.'); setSelected(null); }}>Accept quote</Button>}</div>; })}</div><DialogFooter><Button variant="outline" className="w-full rounded-full" onClick={() => setSelected(null)}>Close</Button></DialogFooter></DialogContent></Dialog></div></DashboardLayout>;

  return <DashboardLayout title="Logistics providers"><div className="mx-auto w-full max-w-6xl space-y-5"><OperationsHeader eyebrow="Verified logistics network" title="Move ready orders from supplier to Nigeria" description="Compare approved pickup, consolidation, air, sea, customs-coordination and local-delivery capabilities. Shipping remains a separate quote from every supplier order." icon={Truck} badge="China to Nigeria" /><div className="grid gap-4 md:grid-cols-2">{providers.map((provider) => <Card key={provider.id} className="rounded-3xl p-5"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-primary/10 text-primary"><Boxes size={19} /></span><Badge variant="success"><CheckCircle2 size={12} /> Verified</Badge></div><h2 className="mt-4 text-lg font-bold">{provider.name}</h2><p className="mt-1 text-xs text-muted-foreground">{provider.cities.join(', ')} · {provider.routes.join(', ')}</p><div className="mt-4 flex flex-wrap gap-1.5">{provider.services.map((item) => <Badge key={item} variant="outline">{item}</Badge>)}</div><div className="mt-4 flex items-center justify-between border-t pt-4 text-xs"><span className="flex items-center gap-1"><Star size={13} className="fill-amber-400 text-amber-400" /> {provider.rating} · {provider.completedShipments} shipments</span><span className="font-semibold">From {money(provider.priceFromMinor)}</span></div><p className="mt-3 text-xs leading-5 text-muted-foreground">{provider.verificationSummary}</p>{provider.linkedAgentId && <div className="mt-3 rounded-xl bg-primary/[.045] p-3 text-xs"><strong>Also provides sourcing support.</strong> Keep sourcing and logistics as separate quotes and evidence records.</div>}<Button className="mt-4 w-full rounded-full" onClick={() => navigate('/app/shipments')}>View shipment options <ArrowRight size={14} /></Button></Card>)}</div><Card className="rounded-3xl border-dashed p-6 text-center"><PackageCheck className="mx-auto text-primary" /><h2 className="mt-3 font-bold">Are your supplier orders ready?</h2><p className="mt-2 text-sm text-muted-foreground">Build one shipment from all ready orders or choose a smaller batch.</p><Button variant="outline" className="mt-4 rounded-full" onClick={() => navigate('/app/shipments')}>Open shipment batches</Button></Card></div></DashboardLayout>;
}
