import { FileText, ShieldCheck } from 'lucide-react';
import { SEOHead } from '../utility/SEOHead';

interface TermsOfServicePageProps { onNavigate: (page: string) => void }

const sections = [
  ['1. About these terms', 'These Terms govern your access to the Naitrust website and waiting list operated by Naitrust Digital Solutions Limited. Naitrust is currently preparing its transaction and verification product for launch. Joining the waiting list does not create a customer account, guarantee access, or require you to purchase anything.'],
  ['2. Waiting-list information', 'You must provide information that is accurate and belongs to you. We may use your submitted contact details to confirm your request and send relevant launch or early-access updates. You may unsubscribe or ask us to remove your waiting-list information.'],
  ['3. Intended Naitrust product', 'Naitrust is being developed to help individuals and businesses create structured deal records, agree terms, review verification information, track evidence, and view payment status supplied through appropriate partners. Product features may change before launch and will be governed by updated terms presented before use.'],
  ['4. Payment and verification boundaries', 'Naitrust is not currently offering public payment custody or public verification through this website. When those services become available, any regulated financial or verification provider involved will be identified, and its applicable terms may also apply. Naitrust is not a bank, deposit-taking institution, insurer, or guarantee of a transaction.'],
  ['5. Acceptable use', 'You must not misuse the website, submit false or unlawful information, impersonate another person or business, interfere with security, attempt unauthorised access, introduce malicious code, or use Naitrust in connection with fraud or illegal activity.'],
  ['6. Intellectual property', 'The Naitrust name, logo, website design, copy, and original materials belong to Naitrust or its licensors. You may use the website for personal evaluation but may not copy, resell, or exploit its materials without permission.'],
  ['7. Availability and liability', 'The website and waiting list are provided on an as-available basis. We work to keep them accurate and secure but cannot promise uninterrupted access. To the extent permitted by law, Naitrust is not liable for decisions or transactions made outside a launched Naitrust service or for losses caused by information supplied by third parties.'],
  ['8. Privacy', 'Our Privacy Policy explains how we collect, use, share, protect, and retain personal information. It forms part of these Terms.'],
  ['9. Changes and governing law', 'We may update these Terms as the product develops. Material terms for a launched service will be presented before they apply. These Terms are governed by the laws of the Federal Republic of Nigeria.'],
];

export function TermsOfServicePage({ onNavigate }: TermsOfServicePageProps) {
  return <div className="min-h-screen bg-background py-12"><SEOHead title="Terms of Service" description="Terms governing the Naitrust website and waiting list." canonicalPath="/terms" /><div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8"><header className="rounded-3xl bg-[#031335] px-6 py-12 text-center text-white"><div className="mx-auto mb-5 flex h-14 w-14 items-center justify-center rounded-2xl bg-white/10"><FileText size={27} /></div><h1 className="text-4xl font-bold">Terms of Service</h1><p className="mx-auto mt-4 max-w-2xl text-blue-100">Clear terms for using the Naitrust website and joining our waiting list.</p><p className="mt-5 text-sm text-blue-200">Effective and last updated: 12 July 2026</p></header><div className="mt-8 rounded-2xl border border-primary/20 bg-primary/5 p-5"><div className="flex gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-primary" /><p className="text-sm leading-6 text-muted-foreground"><strong className="text-foreground">Current status:</strong> Naitrust is accepting waiting-list registrations. Product accounts, verification, safe-deal workflows, and partner-led payment features are not yet publicly available.</p></div></div><div className="mt-8 space-y-5">{sections.map(([title, text]) => <section key={title} className="rounded-2xl border bg-card p-6"><h2 className="text-xl font-bold">{title}</h2><p className="mt-3 text-sm leading-7 text-muted-foreground">{text}</p></section>)}</div><div className="mt-8 flex flex-wrap justify-center gap-3"><button onClick={() => onNavigate('privacy')} className="rounded-full bg-primary px-6 py-3 text-sm font-semibold text-white">Privacy Policy</button><button onClick={() => onNavigate('contact')} className="rounded-full border-2 border-primary px-6 py-3 text-sm font-semibold text-primary">Contact Naitrust</button></div></div></div>;
}
