/**
 * Deal Documents
 * Generates real, customer-friendly PDF documents from a safe deal: the Safe
 * deal agreement and a concise deal summary card. PDFs are drawn directly
 * with jsPDF so downloads remain reliable across browsers.
 *
 * The heavy PDF library is imported dynamically so it only loads when a user
 * actually downloads, keeping it out of the main bundle.
 */

import type { AgreementDraft, DealDeliveryCard, SafeDealDetail } from '../store/types';
import naitrustLogo from '../../assets/naitrust-logo/naitrust-icon-3.png';
import type { jsPDF as JsPdfDocument } from 'jspdf';
import {
  formatMinorAmount,
  getStatusPresentation,
  partyModeLabel,
  roleLabel,
} from './safe-deal-presentation';

function formatDate(iso: string): string {
  try {
    return new Date(iso).toLocaleDateString('en-NG', { year: 'numeric', month: 'long', day: 'numeric' });
  } catch {
    return iso;
  }
}

function formatDateTime(iso: string): string {
  try {
    return new Date(iso).toLocaleString('en-NG', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
    });
  } catch {
    return iso;
  }
}

/** Filesystem-friendly slug from a deal reference. */
function slug(reference: string): string {
  return reference.replace(/[^a-zA-Z0-9._-]+/g, '-');
}

async function logoDataUrl(): Promise<string> {
  const blob = await fetch(naitrustLogo).then((response) => response.blob());
  return await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(blob);
  });
}

async function brandedPdf(kicker: string, title: string, subtitle?: string): Promise<{ pdf: JsPdfDocument; y: number }> {
  const { jsPDF } = await import('jspdf');
  const pdf = new jsPDF({ unit: 'pt', format: 'a4', orientation: 'portrait' });
  pdf.addImage(await logoDataUrl(), 'PNG', 44, 38, 28, 28);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(17);
  pdf.setTextColor('#1e90ff');
  pdf.text('Naitrust', 82, 59);
  pdf.setFontSize(9);
  pdf.setTextColor('#64748b');
  pdf.text(kicker.toUpperCase(), 44, 88);
  pdf.setFontSize(22);
  pdf.setTextColor('#071b31');
  pdf.text(title, 44, 118, { maxWidth: 505 });
  let y = 140;
  if (subtitle) {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(10);
    pdf.setTextColor('#64748b');
    pdf.text(subtitle, 44, y, { maxWidth: 505 });
    y += 22;
  }
  return { pdf, y };
}

function ensurePdfSpace(pdf: JsPdfDocument, y: number, needed = 80): number {
  if (y + needed <= 790) return y;
  pdf.addPage();
  return 48;
}

function pdfSection(pdf: JsPdfDocument, heading: string, body: string, y: number): number {
  y = ensurePdfSpace(pdf, y, 90);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.setTextColor('#071b31');
  pdf.text(heading, 44, y);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10.5);
  pdf.setTextColor('#334155');
  const lines = pdf.splitTextToSize(body || 'Not available', 500) as string[];
  pdf.text(lines, 44, y + 18);
  return y + 22 + lines.length * 14;
}

/** Download an agreement while the deal is still on the review screen. */
export async function downloadAgreementDraft(input: { agreement: AgreementDraft; title: string; amountMinor: number; currency: string }): Promise<void> {
  const { pdf, y: startY } = await brandedPdf('Protected Deal agreement preview', input.title, `${formatMinorAmount(input.amountMinor, input.currency)} · Agreement v${input.agreement.version}`);
  let y = startY + 12;
  input.agreement.sections.forEach((section, index) => { y = pdfSection(pdf, `${index + 1}. ${section.heading}`, section.body, y); });
  pdf.setFontSize(9); pdf.setTextColor('#94a3b8'); pdf.text(`Generated by Naitrust on ${formatDate(new Date().toISOString())}.`, 44, ensurePdfSpace(pdf, y + 12, 20));
  pdf.save(`naitrust-agreement-v${input.agreement.version}-${slug(input.title || 'protected-deal')}.pdf`);
}

/** Download the Safe deal agreement as a PDF. */
export async function downloadAgreementDocument(deal: SafeDealDetail): Promise<void> {
  const { pdf, y: startY } = await brandedPdf('Protected Deal agreement', deal.title, `${deal.reference} · ${partyModeLabel(deal.partyMode)} · ${formatMinorAmount(deal.amountMinor, deal.currency)}`);
  let y = pdfSection(pdf, 'Parties', deal.parties.map((party) => `${party.name} — ${roleLabel(party.role)} (${party.status})`).join('\n'), startY + 10);
  y = pdfSection(pdf, 'Deal dates', `Created: ${formatDate(deal.createdAt)}\nDelivery due: ${deal.deliveryDueDate ? formatDate(deal.deliveryDueDate) : 'Not available'}\nAgreement version: v${deal.agreement.version}`, y);
  deal.agreement.sections.forEach((section, index) => { y = pdfSection(pdf, `${index + 1}. ${section.heading}`, section.body, y); });
  y = pdfSection(pdf, 'Release conditions', deal.releaseConditions, y);
  pdf.setFontSize(9); pdf.setTextColor('#94a3b8'); pdf.text(`Generated by Naitrust for ${deal.reference}.`, 44, ensurePdfSpace(pdf, y + 12, 20));
  pdf.save(`naitrust-agreement-${slug(deal.reference)}.pdf`);
}

/** Download a concise deal summary card as a PDF. */
export async function downloadDealSummaryCard(deal: SafeDealDetail): Promise<void> {
  const status = getStatusPresentation(deal.status);
  const you = deal.parties.find((p) => p.isYou);
  const other = deal.parties.find((p) => !p.isYou);

  const { pdf, y: startY } = await brandedPdf('Deal summary', deal.title, `${deal.reference} · ${status.label}`);
  let y = pdfSection(pdf, 'Protected amount', formatMinorAmount(deal.amountMinor, deal.currency), startY + 10);
  y = pdfSection(pdf, 'Parties', `You: ${you ? `${you.name} — ${roleLabel(you.role)}` : 'Not available'}\nCounterparty: ${other ? `${other.name} — ${roleLabel(other.role)}` : deal.counterpartyName}`, y);
  y = pdfSection(pdf, 'Deal details', `Type: ${partyModeLabel(deal.partyMode)}\nCreated: ${formatDate(deal.createdAt)}\nDelivery due: ${deal.deliveryDueDate ? formatDate(deal.deliveryDueDate) : 'Not available'}`, y);
  y = pdfSection(pdf, 'Funding', `${formatMinorAmount(deal.funding.amountReceivedMinor, deal.funding.currency)} received of ${formatMinorAmount(deal.funding.amountExpectedMinor, deal.funding.currency)} expected. Protected with ${deal.funding.partner}.`, y);
  y = pdfSection(pdf, "What's protected", deal.description || deal.releaseConditions, y);
  pdf.setFontSize(9); pdf.setTextColor('#94a3b8'); pdf.text(`Generated by Naitrust for ${deal.reference}.`, 44, ensurePdfSpace(pdf, y + 12, 20));
  pdf.save(`naitrust-deal-${slug(deal.reference)}.pdf`);
}

export interface DeliveryCardDocumentInput {
  title: string;
  reference: string;
  card: DealDeliveryCard;
  handoverUrl: string;
}

/** Download the limited delivery card. No financial or party data is included. */
export async function downloadDeliveryCardPdf(input: DeliveryCardDocumentInput): Promise<void> {
  const [{ toDataURL }, { jsPDF }] = await Promise.all([import('qrcode'), import('jspdf')]);
  const qrDataUrl = await toDataURL(input.handoverUrl, {
    errorCorrectionLevel: 'H',
    margin: 1,
    width: 280,
    color: { dark: '#071b31', light: '#ffffff' },
  });
  const logoBlob = await fetch(naitrustLogo).then((response) => response.blob());
  const logoDataUrl = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(String(reader.result));
    reader.onerror = () => reject(reader.error);
    reader.readAsDataURL(logoBlob);
  });
  const pdf = new jsPDF({ unit: 'pt', format: 'a4', orientation: 'portrait' });
  const navy = '#071b31';
  pdf.setFillColor(navy);
  pdf.roundedRect(36, 32, 523, 112, 14, 14, 'F');
  pdf.addImage(logoDataUrl, 'PNG', 58, 50, 30, 30);
  pdf.setTextColor('#ffffff');
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text('Naitrust', 98, 70);
  pdf.setFontSize(10);
  pdf.setTextColor('#9fb0c2');
  pdf.text('SECURE PRODUCT HANDOVER', 58, 100);
  pdf.setFontSize(17);
  pdf.setTextColor('#ffffff');
  pdf.text(input.title, 58, 123, { maxWidth: 470 });

  pdf.setTextColor(navy);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Deal reference ${input.reference}`, 48, 170);
  pdf.setDrawColor('#dbeafe');
  pdf.setFillColor('#f8fbff');
  pdf.roundedRect(40, 188, 515, 230, 12, 12, 'FD');
  pdf.addImage(qrDataUrl, 'PNG', 65, 215, 175, 175);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(9);
  pdf.setTextColor('#64748b');
  pdf.text('HANDOVER OTP', 282, 250);
  pdf.setTextColor(navy);
  pdf.setFontSize(27);
  pdf.text(input.card.otpCode.split('').join('  '), 282, 287);
  pdf.setTextColor('#64748b');
  pdf.setFontSize(9);
  pdf.text('CARD EXPIRES', 282, 330);
  pdf.setTextColor(navy);
  pdf.setFontSize(12);
  pdf.text(formatDateTime(input.card.expiresAt), 282, 351, { maxWidth: 235 });

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(11);
  pdf.text('BUYER INSTRUCTIONS', 48, 458);
  const instructions = [
    'Check the package, model, seal and serial or IMEI with the rider present.',
    'Scan this QR or enter the six-digit OTP in your Naitrust Transaction Room.',
    'Confirm the correct product or report a problem during the handover review.',
  ];
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(11);
  instructions.forEach((instruction, index) => pdf.text(`${index + 1}. ${instruction}`, 56, 488 + index * 34, { maxWidth: 485 }));
  pdf.setFillColor('#eaf7f3');
  pdf.roundedRect(44, 594, 507, 58, 9, 9, 'F');
  pdf.setTextColor('#14532d');
  pdf.setFontSize(10);
  pdf.text('Confirming receipt starts product checks. It does not release payment or waive defect or consumer rights.', 58, 619, { maxWidth: 475 });
  pdf.setTextColor('#94a3b8');
  pdf.setFontSize(9);
  pdf.text('This one-time card is valid only for the intended buyer account and becomes invalid after use, expiry or regeneration.', 48, 700, { maxWidth: 500 });
  pdf.save(`naitrust-delivery-${slug(input.reference)}.pdf`);
}
