import { BriefcaseBusiness, Building2, Car, Hammer, HeartHandshake, Home, PackageCheck, Plane, ShoppingBag, Smartphone } from 'lucide-react';

export const useCases = [
  { slug: 'supplier-orders', icon: PackageCheck, title: 'Supplier and wholesale orders', audience: 'Retailers, distributors and procurement teams', summary: 'Create a clearer record for bulk stock and supplier orders before committing money.', problem: 'Buyers often discover suppliers through referrals, markets, WhatsApp or social media, then transfer large amounts with limited proof of stock, delivery dates or refund expectations.', flow: ['Identify the buyer, supplier and their roles', 'Record products, quantities, amount and delivery dates', 'Agree the evidence required before completion', 'Keep payment status, invoices and delivery proof together'], evidence: ['Supplier identity or business information', 'Quotation or invoice', 'Stock or inspection evidence', 'Waybill and delivery confirmation'] },
  { slug: 'contractor-projects', icon: Hammer, title: 'Contractor and construction work', audience: 'Property owners, SMEs and contractors', summary: 'Turn an informal job agreement into a visible scope, timeline and evidence trail.', problem: 'Projects can fail when the scope, materials, milestones and completion standard exist only in chats or verbal conversations.', flow: ['Define the work, price and responsibilities', 'Record materials, dates and completion expectations', 'Attach progress evidence to the same deal', 'Confirm completion or record an issue clearly'], evidence: ['Scope of work', 'Material list and receipts', 'Progress photos', 'Handover or completion approval'] },
  { slug: 'social-commerce', icon: Smartphone, title: 'Social storefront sales', audience: 'Instagram, WhatsApp, TikTok and Facebook sellers', summary: 'Help buyers distinguish a genuine seller and understand the order before paying.', problem: 'Social buyers may see attractive products but have little confidence that the account, product or payment instruction is genuine.', flow: ['Connect the order to a known seller identity', 'Record the exact item, price and delivery promise', 'Keep payment and dispatch status visible', 'Attach delivery evidence and buyer confirmation'], evidence: ['Seller identity or business details', 'Product description and order summary', 'Dispatch receipt or tracking', 'Delivery confirmation'] },
  { slug: 'high-value-personal-purchases', icon: ShoppingBag, title: 'High-value personal purchases', audience: 'Individuals buying electronics, equipment or valuable goods', summary: 'Document the item, condition and delivery expectations before a serious purchase.', problem: 'A buyer can lose money when an expensive item does not exist, differs from its description or is never delivered.', flow: ['Record the item and seller', 'Agree price, condition and inspection rules', 'Keep relevant payment status and evidence together', 'Confirm receipt or raise an issue from the record'], evidence: ['Item photos and serial information', 'Inspection notes', 'Receipt or invoice', 'Collection or delivery confirmation'] },
  { slug: 'freelance-agency-work', icon: BriefcaseBusiness, title: 'Freelance and agency projects', audience: 'Clients, freelancers, studios and agencies', summary: 'Give both sides a shared record of deliverables, deadlines and approvals.', problem: 'Clients fear paying before work is delivered while service providers fear completing work without a clear approval or payment record.', flow: ['Define deliverables and deadlines', 'Record review and approval expectations', 'Attach submissions and feedback', 'Confirm completion in the same record'], evidence: ['Proposal or brief', 'Deliverable links or files', 'Revision history', 'Client approval'] },
  { slug: 'event-vendors', icon: HeartHandshake, title: 'Events and advance bookings', audience: 'Clients, planners, caterers, decorators and photographers', summary: 'Keep long-lead bookings and vendor commitments understandable from deposit to event day.', problem: 'Event services are often booked months ahead with deposits, changing requirements and limited proof of what the vendor promised.', flow: ['Record the event, vendor and agreed package', 'Set dates, deliverables and responsibilities', 'Attach receipts and preparation evidence', 'Confirm service delivery or document a problem'], evidence: ['Package or quotation', 'Deposit receipt', 'Schedule and preparation updates', 'Event-day completion evidence'] },
  { slug: 'property-agent-payments', icon: Home, title: 'Property and agent transactions', audience: 'Renters, buyers, landlords and agents', summary: 'Organise identity, property information and agreed fees before property-related payments.', problem: 'Fake listings and unclear agent authority can expose people to fraudulent inspection fees, deposits or rent payments.', flow: ['Identify the parties and their claimed roles', 'Record the property and purpose of payment', 'Agree the documents and confirmation required', 'Keep viewing, payment and agreement evidence together'], evidence: ['Agent or owner identity', 'Property information', 'Viewing confirmation', 'Agreement and payment receipt'] },
  { slug: 'vehicle-transactions', icon: Car, title: 'Vehicle purchases and deposits', audience: 'Individual buyers, dealers and vehicle owners', summary: 'Record the vehicle, seller, inspection and handover expectations before payment.', problem: 'Vehicle buyers may face false ownership claims, undisclosed condition issues or disputes about deposits and delivery.', flow: ['Identify the seller and vehicle', 'Record price, deposit and inspection conditions', 'Attach inspection and ownership evidence', 'Confirm handover and completion'], evidence: ['Vehicle identifiers', 'Inspection report', 'Ownership documents', 'Handover confirmation'] },
  { slug: 'diaspora-purchases', icon: Plane, title: 'Diaspora-to-Nigeria purchases', audience: 'Overseas buyers, families and Nigerian vendors', summary: 'Give remote buyers a clearer view of a local purchase or service.', problem: 'People abroad often rely on relatives, screenshots and fragmented updates when paying Nigerian vendors from a distance.', flow: ['Identify the local parties and purpose', 'Record the amount, item or service and timeline', 'Collect progress or delivery evidence', 'Keep confirmation accessible to the remote buyer'], evidence: ['Vendor information', 'Quotation and payment record', 'Progress or dispatch evidence', 'Recipient confirmation'] },
  { slug: 'business-service-providers', icon: Building2, title: 'Business service providers', audience: 'Consultants, accountants, designers and professional firms', summary: 'Create accountability around recurring or outcome-based professional services.', problem: 'Professional engagements can become difficult when responsibilities, access, documents and acceptance criteria are not clearly recorded.', flow: ['Define the engagement and responsible people', 'Agree outputs, dates and required access', 'Attach work evidence and decisions', 'Record acceptance and completion'], evidence: ['Engagement letter or proposal', 'Required documents', 'Work submissions', 'Acceptance record'] },
] as const;

export type UseCase = (typeof useCases)[number];
