import { Building2, Car, Hammer, Home, KeyRound, Landmark, MapPin, WalletCards } from 'lucide-react';

/**
 * Real estate is the launch market. Slugs remain stable where an existing
 * transaction flow already uses them, preserving saved drafts/API payloads.
 */
export const useCases = [
  { slug: 'property-agent-payments', icon: Home, title: 'Property purchases and deposits', audience: 'Property buyers, sellers, agents and developers', summary: 'Create a clear record of the property, participants, agreed amount, deposits, documents and transaction milestones.', problem: 'Property payments can be made after informal conversations without a shared record of the property, the recipient’s role, the documents promised, or the conditions attached to the payment.', flow: ['Identify the property and every participant', 'Record the price, deposit, payment plan and responsibilities', 'Attach property documents, receipts and inspection evidence', 'Confirm milestones, completion, or document an issue'], evidence: ['Participant identity or business details', 'Property description and location', 'Offer, allocation, title or supporting documents', 'Payment receipts and completion confirmation'] },
  { slug: 'developer-instalments', icon: Building2, title: 'Developer instalment plans', audience: 'Buyers, developers and real estate companies', summary: 'Keep instalment schedules, receipts, property progress and outstanding commitments in one transaction record.', problem: 'Long-running payment plans become difficult to verify when receipts, balance updates, allocation information and project progress are spread across emails and chats.', flow: ['Record the development, unit and parties', 'Set the instalment schedule and expected documents', 'Attach payment confirmations and progress updates', 'Maintain the balance and completion history'], evidence: ['Developer or company verification', 'Offer or allocation letter', 'Instalment schedule and receipts', 'Construction progress and handover records'] },
  { slug: 'land-transactions', icon: MapPin, title: 'Land transactions', audience: 'Land buyers, sellers, agents and family representatives', summary: 'Document the land description, claimed ownership, participants, payments and evidence reviewed during the transaction.', problem: 'Land transactions may involve several representatives, unclear authority, inconsistent descriptions and payment demands that are difficult to reconcile later.', flow: ['Record the land description and location', 'Identify sellers, agents and representatives', 'Document the agreed amount and payment stages', 'Attach reviewed evidence and completion activity'], evidence: ['Survey or location information', 'Seller and representative identity', 'Ownership or authority documents supplied', 'Payment and handover confirmations'] },
  { slug: 'agent-led-property', icon: KeyRound, title: 'Agent-led property transactions', audience: 'Property buyers, sellers, landlords and agents', summary: 'Make the agent’s role, fees, authority and transaction activity visible to the people involved.', problem: 'Buyers may not know whether an agent is authorised, who should receive a payment, or which promises came from the owner, developer or intermediary.', flow: ['Identify the agent and represented party', 'Record the property and purpose of each payment', 'Agree fees, responsibilities and required confirmation', 'Keep communication and evidence with the transaction'], evidence: ['Agent identity or business profile', 'Owner or developer authority supplied', 'Viewing or inspection confirmation', 'Fee and payment receipts'] },
  { slug: 'contractor-projects', icon: Hammer, title: 'Construction and renovation milestones', audience: 'Property owners, developers and contractors', summary: 'Turn a construction agreement into a visible scope, milestone plan, payment record and evidence trail.', problem: 'Projects become disputed when scope, materials, milestones, payment stages and completion standards exist only in chats or verbal conversations.', flow: ['Define the work, price and responsibilities', 'Record materials, milestones and payment stages', 'Attach progress evidence to the transaction', 'Confirm completion or record an issue clearly'], evidence: ['Scope of work and drawings', 'Material list and receipts', 'Progress photos and inspections', 'Handover or completion approval'] },
  { slug: 'diaspora-purchases', icon: Landmark, title: 'Diaspora property purchases', audience: 'Overseas buyers and Nigerian property participants', summary: 'Give remote buyers one accessible record of the local property transaction, participants, payments and progress.', problem: 'Overseas buyers often rely on relatives, screenshots and fragmented updates while making substantial property payments from a distance.', flow: ['Identify the local parties and property', 'Record the amount, documents and timeline', 'Collect inspection, payment and progress evidence', 'Keep confirmations accessible to the remote buyer'], evidence: ['Participant verification', 'Property and inspection information', 'Agreement and payment record', 'Progress, allocation, or handover confirmation'] },
  { slug: 'vehicle-transactions', icon: Car, title: 'Vehicle transactions — coming later', audience: 'Individual buyers, dealers and vehicle owners', summary: 'A future application of the same transaction-record infrastructure for high-value vehicle purchases.', problem: 'Vehicle buyers can face unclear ownership, condition, deposit and delivery claims.', flow: ['Identify the seller and vehicle', 'Record price and inspection conditions', 'Attach ownership and inspection evidence', 'Confirm handover'], evidence: ['Vehicle identifiers', 'Inspection report', 'Ownership documents', 'Handover confirmation'] },
  { slug: 'high-value-personal-purchases', icon: WalletCards, title: 'Other high-value assets — coming later', audience: 'People completing significant non-property purchases', summary: 'A future use of Naitrust for transactions where identity, terms, payment records and evidence matter.', problem: 'High-value purchases become harder to resolve when the agreement and evidence are fragmented.', flow: ['Identify participants and the asset', 'Record terms and payment conditions', 'Attach relevant evidence', 'Confirm completion'], evidence: ['Participant details', 'Asset description', 'Agreement and receipt', 'Completion evidence'] },
] as const;

export type UseCase = (typeof useCases)[number];
