import {
  Boxes,
  Briefcase,
  Building2,
  Car,
  Cog,
  Factory,
  FileText,
  Hammer,
  Home,
  KeyRound,
  Landmark,
  MapPin,
  Package,
  Ship,
  Truck,
  WalletCards,
  Wrench,
} from 'lucide-react';

/**
 * Property was the launch market; the catalog now spans general business
 * deals too. Slugs remain stable where an existing transaction flow already
 * uses them, preserving saved drafts/API payloads.
 */
export const useCases = [
  { slug: 'property-agent-payments', icon: Home, title: 'Property purchases and deposits', audience: 'Property buyers, sellers, agents and developers', summary: 'Create a clear record of the property, participants, agreed amount, deposits, documents and transaction milestones.', problem: 'Property payments can be made after informal conversations without a shared record of the property, the recipient’s role, the documents promised, or the conditions attached to the payment.', flow: ['Identify the property and every participant', 'Record the price, deposit, payment plan and responsibilities', 'Attach property documents, receipts and inspection evidence', 'Confirm milestones, completion, or document an issue'], evidence: ['Participant identity or business details', 'Property description and location', 'Offer, allocation, title or supporting documents', 'Payment receipts and completion confirmation'] },
  { slug: 'developer-instalments', icon: Building2, title: 'Developer instalment plans', audience: 'Buyers, developers and real estate companies', summary: 'Keep instalment schedules, receipts, property progress and outstanding commitments in one transaction record.', problem: 'Long-running payment plans become difficult to verify when receipts, balance updates, allocation information and project progress are spread across emails and chats.', flow: ['Record the development, unit and parties', 'Set the instalment schedule and expected documents', 'Attach payment confirmations and progress updates', 'Maintain the balance and completion history'], evidence: ['Developer or company verification', 'Offer or allocation letter', 'Instalment schedule and receipts', 'Construction progress and handover records'] },
  { slug: 'land-transactions', icon: MapPin, title: 'Land transactions', audience: 'Land buyers, sellers, agents and family representatives', summary: 'Document the land description, claimed ownership, participants, payments and evidence reviewed during the transaction.', problem: 'Land transactions may involve several representatives, unclear authority, inconsistent descriptions and payment demands that are difficult to reconcile later.', flow: ['Record the land description and location', 'Identify sellers, agents and representatives', 'Document the agreed amount and payment stages', 'Attach reviewed evidence and completion activity'], evidence: ['Survey or location information', 'Seller and representative identity', 'Ownership or authority documents supplied', 'Payment and handover confirmations'] },
  { slug: 'agent-led-property', icon: KeyRound, title: 'Agent-led property transactions', audience: 'Property buyers, sellers, landlords and agents', summary: 'Make the agent’s role, fees, authority and transaction activity visible to the people involved.', problem: 'Buyers may not know whether an agent is authorised, who should receive a payment, or which promises came from the owner, developer or intermediary.', flow: ['Identify the agent and represented party', 'Record the property and purpose of each payment', 'Agree fees, responsibilities and required confirmation', 'Keep communication and evidence with the transaction'], evidence: ['Agent identity or business profile', 'Owner or developer authority supplied', 'Viewing or inspection confirmation', 'Fee and payment receipts'] },
  { slug: 'contractor-projects', icon: Hammer, title: 'Construction and renovation milestones', audience: 'Property owners, developers and contractors', summary: 'Turn a construction agreement into a visible scope, milestone plan, payment record and evidence trail.', problem: 'Projects become disputed when scope, materials, milestones, payment stages and completion standards exist only in chats or verbal conversations.', flow: ['Define the work, price and responsibilities', 'Record materials, milestones and payment stages', 'Attach progress evidence to the transaction', 'Confirm completion or record an issue clearly'], evidence: ['Scope of work and drawings', 'Material list and receipts', 'Progress photos and inspections', 'Handover or completion approval'] },
  { slug: 'diaspora-purchases', icon: Landmark, title: 'Diaspora property purchases', audience: 'Overseas buyers and Nigerian property participants', summary: 'Give remote buyers one accessible record of the local property transaction, participants, payments and progress.', problem: 'Overseas buyers often rely on relatives, screenshots and fragmented updates while making substantial property payments from a distance.', flow: ['Identify the local parties and property', 'Record the amount, documents and timeline', 'Collect inspection, payment and progress evidence', 'Keep confirmations accessible to the remote buyer'], evidence: ['Participant verification', 'Property and inspection information', 'Agreement and payment record', 'Progress, allocation, or handover confirmation'] },
  { slug: 'vehicle-transactions', icon: Car, title: 'Vehicle transactions', audience: 'Individual buyers, dealers and vehicle owners', summary: 'Record the parties, payment terms, inspection evidence and handover for a vehicle purchase.', problem: 'Vehicle buyers can face unclear ownership, condition, deposit and delivery claims.', flow: ['Identify the seller and vehicle', 'Record price and inspection conditions', 'Attach ownership and inspection evidence', 'Confirm handover'], evidence: ['Vehicle identifiers', 'Inspection report', 'Ownership documents', 'Handover confirmation'] },
  { slug: 'high-value-personal-purchases', icon: WalletCards, title: 'Product purchases', audience: 'People buying food, fashion, gadgets, household items, or other products', summary: 'Protect payment for a product until it is delivered and checked against what was agreed.', problem: 'Buying from a new seller can lead to non-delivery, damaged goods, missing contents, or a product that differs from the description.', flow: ['Identify the seller and product', 'Record the item, price, and delivery terms', 'Attach relevant dispatch and receipt evidence', 'Confirm delivery or report a problem'], evidence: ['Seller identity or business details', 'Product description or order', 'Dispatch or handover evidence', 'Condition-on-arrival evidence where needed'] },
  { slug: 'supplier-purchase', icon: Package, title: 'Supplier purchases', audience: 'Retailers, traders and businesses buying stock from suppliers', summary: 'Pay a supplier with clear terms, confirm delivery, and release payment only when the order arrives as agreed.', problem: 'Paying a new or unfamiliar supplier in advance carries real risk: goods may arrive late, incomplete, or not at all, with no structured way to resolve it.', flow: ['Identify the supplier and the order', 'Record the price, quantity and delivery terms', 'Attach invoices, waybills and delivery evidence', 'Confirm receipt or raise a dispute'], evidence: ['Supplier identity or business details', 'Invoice or purchase order', 'Waybill or delivery confirmation', 'Goods-received confirmation'] },
  { slug: 'wholesale-order', icon: Boxes, title: 'Wholesale orders', audience: 'Wholesalers, distributors and bulk buyers', summary: 'Protect large bulk-order payments with agreed quantities, pricing and delivery milestones.', problem: 'Wholesale orders often involve large upfront payments and multi-stage delivery, making it hard to track what has been paid, delivered, or is still outstanding.', flow: ['Record the order, quantities and unit pricing', 'Set delivery stages for large or split orders', 'Attach delivery and inspection evidence at each stage', 'Confirm completion or record a shortfall'], evidence: ['Order confirmation', 'Delivery notes per stage', 'Quantity/quality inspection records', 'Final reconciliation'] },
  { slug: 'contractor-engagement', icon: Wrench, title: 'Contractor engagements', audience: 'Businesses and individuals hiring contractors or freelancers', summary: 'Set clear scope and payment terms with a contractor, and release payment as work is confirmed complete.', problem: 'Hiring a contractor for the first time means paying for work that has not started, with no shared record of scope, timeline, or what "done" means.', flow: ['Define the scope of work and price', 'Agree milestones or a single completion payment', 'Attach progress evidence as work proceeds', 'Confirm completion or raise a dispute'], evidence: ['Contractor identity or business profile', 'Scope of work agreement', 'Progress evidence', 'Completion sign-off'] },
  { slug: 'service-delivery', icon: Briefcase, title: 'Service delivery', audience: 'Service providers and the businesses or individuals paying them', summary: "Pay for a service once and confirm it was delivered as agreed before releasing funds.", problem: "Paying for a service upfront: consulting, design, repair, logistics support: leaves the payer with no recourse if the service isn't delivered as promised.", flow: ['Describe the service and agreed outcome', 'Record the price and delivery timeline', 'Attach evidence the service was delivered', 'Confirm completion or raise a dispute'], evidence: ['Service provider identity', 'Agreed scope and price', 'Delivery or completion evidence', 'Sign-off or feedback'] },
  { slug: 'equipment-purchase', icon: Cog, title: 'Equipment purchases', audience: 'Businesses buying machinery, tools or equipment', summary: 'Protect a payment for equipment until it arrives, is inspected, and matches what was agreed.', problem: 'Buying equipment from an unfamiliar seller risks paying for goods that arrive damaged, wrong, or not at all.', flow: ['Identify the seller and the equipment', 'Record price, specification and delivery terms', 'Attach inspection and delivery evidence', 'Confirm acceptance or raise a dispute'], evidence: ['Seller identity or business details', 'Equipment specification', 'Delivery and inspection evidence', 'Acceptance confirmation'] },
  { slug: 'logistics-agreement', icon: Truck, title: 'Logistics agreements', audience: 'Businesses moving goods and the transporters or logistics providers they hire', summary: 'Protect payment for haulage, freight or delivery services until goods arrive as agreed.', problem: 'Paying a transporter or logistics provider upfront carries risk if goods are delayed, damaged, or never delivered.', flow: ['Record the goods, route and delivery terms', 'Agree the price and delivery deadline', 'Attach pickup, transit and delivery evidence', 'Confirm delivery or raise a dispute'], evidence: ['Transporter identity or business details', 'Waybill or manifest', 'Pickup and delivery confirmation', 'Condition-on-arrival evidence'] },
  { slug: 'manufacturing-order', icon: Factory, title: 'Manufacturing orders', audience: 'Businesses commissioning custom-made or manufactured goods', summary: 'Protect payment for a manufacturing order across production milestones, from deposit to finished goods.', problem: 'Custom manufacturing orders often require staged payments before goods exist, with little visibility into production progress.', flow: ['Record the order specification and price', 'Set production milestones and payment stages', 'Attach production progress and quality evidence', 'Confirm final delivery or raise a dispute'], evidence: ['Manufacturer identity or business details', 'Order specification', 'Production milestone evidence', 'Final quality and delivery confirmation'] },
  { slug: 'import-export', icon: Ship, title: 'Import and export transactions', audience: 'Importers, exporters and their overseas or local counterparties', summary: 'Protect cross-border trade payments with clear terms, shipping evidence and confirmed delivery.', problem: 'Import and export deals combine large payments, distance, and unfamiliar counterparties: a difficult combination to trust without a structured record.', flow: ['Record the goods, parties and agreed terms', 'Set the payment schedule against shipping milestones', 'Attach shipping, customs and delivery evidence', 'Confirm receipt or raise a dispute'], evidence: ['Counterparty identity or business details', 'Commercial invoice and shipping documents', 'Customs and transit evidence', 'Delivery confirmation'] },
  { slug: 'custom-business-deal', icon: FileText, title: 'Custom business deals', audience: "Any business or individual with a transaction that doesn't fit a standard category", summary: 'Define your own terms, deliverables and release conditions for a business deal that needs payment protection.', problem: "Not every business transaction fits a template: but any deal involving an unfamiliar counterparty still needs clear terms and a protected payment.", flow: ["Describe the deal and what's being exchanged", 'Set the price and your own release conditions', 'Attach whatever evidence the deal requires', 'Confirm completion or raise a dispute'], evidence: ['Counterparty identity or business details', 'Agreed terms', 'Evidence relevant to the deal', 'Completion confirmation'] },
] as const;

export type UseCase = (typeof useCases)[number];
