import type { PolicySection } from '../components/pieces/general/PolicyPage';
import { serviceInformation as service } from './service-information';
import { legalTermsSections } from '../features/legal/terms';

export const privacySections: PolicySection[] = [
  { title: 'Who we are and what this notice covers', paragraphs: [
    `${service.company} operates Naitrust and is responsible for the personal information it collects for its website, early access list, product preview and support. Contact ${service.contact} with the subject “Privacy request” to reach the team responsible for privacy.`,
    'This notice addresses personal information under the Nigeria Data Protection Act 2023 and applicable requirements. It distinguishes information used today from information required for planned payment and verification services. Joining the waiting list does not require a BVN, NIN, identity document, payment card or liveness photograph. Do not send those details in a public form.',
  ] },
  { title: 'Information collected through the website', paragraphs: ['We collect the information you submit and the technical information needed to operate the website.'], bullets: [
    'Early access: name, email, phone if provided, account interest, business name where relevant, intended transactions, expectations and your communication consent.',
    'Contact, feedback and complaints: contact details, subject, message, references and any information you choose to include. Include only information relevant to the request.',
    'Website operation: network and device information made available to our hosting systems, page requests, error information, language and cookie preferences. Necessary browser storage also supports sign in and security.',
    'Invited previews: account and session information, settings and the terms, messages or evidence you enter. Records and balances in the test workspace are fictional. Use sample information only.',
  ] },
  { title: 'Data for planned account, payment and verification services', paragraphs: [
    'When a service becomes available, its collection notice will identify the information needed, purpose, provider, sharing and retention arrangements before you submit it. Depending on the service, this may include identity and contact details, business registration and representative authority, beneficiary account details, payment references, transaction records and compliance checks.',
    'A Protected Deal may contain the agreement, parties, amount, delivery information, evidence, messages, approvals and issue reports. Relevant deal information is shared with the other authorised participants. Do not upload unrelated personal information or documents you have no authority to share.',
    'A payment provider may process payment credentials under its own notice. Naitrust’s support team will never ask for your password, OTP, transaction PIN or full card security details.',
  ] },
  { title: 'Why we use information', paragraphs: [
    'We use submitted details to manage early access requests, answer enquiries, provide requested features, investigate complaints, protect the service and maintain necessary records. We use consent for optional marketing and optional cookies; service administration may instead be necessary for a requested service, a legal obligation or a legitimate interest such as preventing abuse.',
    'The applicable basis depends on the purpose and circumstances. We consider your rights when relying on legitimate interests. Where we rely on consent, you may withdraw it without invalidating earlier lawful processing. Declining optional marketing does not prevent you from contacting support.',
  ] },
  { title: 'Liveness, photographs and sensitive information', paragraphs: [
    'The planned deal workflow uses a fresh camera based liveness check for creating or accepting a Protected Deal. A facial image or verification result may be sensitive personal data. The collection screen must explain the purpose and required consent or other applicable basis before capture.',
    'A deal specific capture is tied to that deal and is not a public profile photograph. The planned sharing model permits the authenticated intended recipient or accepted participants to view it for identity checking, as explained before capture. Unauthenticated invitation previews must not expose the image.',
    'The intended participant access period ends 90 days after deal closure unless a dispute, investigation or lawful preservation requirement applies. This is an access limit, not a promise that every related record is deleted on that date. Final provider storage and deletion arrangements will be disclosed before live collection.',
  ] },
  { title: 'Sharing and service providers', paragraphs: [
    'Information may be handled by hosting, communications, support and security providers as needed to operate the service. Future identity and payment providers will be identified for the relevant feature before live use. A provider may have its own responsibilities and privacy notice.',
    'Deal participants receive information relevant to their deal. In the optional legal review preview, both parties authorise the named reviewer to access the agreement, existing evidence and future room documents. Private messages, banking details and identity captures are outside that grant, unless you include them in an uploaded document. Both parties confirm ordinary deactivation; contact support for an urgent privacy or access concern. Copies already obtained cannot be recalled.',
    'Information may also be disclosed when legally required or necessary to investigate misuse, protect rights or resolve a complaint. We do not sell your personal data.',
  ] },
  { title: 'Storage, international processing and retention', paragraphs: [
    'Hosting or service providers may process information outside Nigeria. Any transfer must have an applicable lawful basis and appropriate safeguards. Provider locations and safeguards for new sensitive data or payment services must be assessed and disclosed before those services launch.',
    'Early access details are retained while needed to manage your request and launch communications; ask to unsubscribe or have them removed. Support and complaint records are retained while needed to resolve the matter and meet applicable obligations. Necessary security and consent records may need to be kept after a deletion request.',
    'For live services, retention depends on the record, purpose, applicable law, provider requirements and any active dispute or legal hold. We will explain any lawful reason for retaining information when responding to a deletion request. No single retention period applies to all records.',
  ] },
  { title: 'Cookies and browser storage', paragraphs: [
    'Necessary cookies and browser storage support sessions, security, language and your consent choices. Optional analytics, marketing and social preferences start switched off. You can accept, reject or change optional choices through Cookie preferences in the footer. Closing the banner does not give consent.',
    'The current website does not load optional analytics or advertising trackers. Saving an optional preference records your choice; it does not itself activate a service. Any future optional tracker must respect that choice and have its purpose explained before use. Cookie choices are saved for up to one year; browser settings can remove them sooner.',
  ] },
  { title: 'Your choices and rights', paragraphs: [
    `Contact ${service.contact} to request access, correction, deletion, restriction or portability, object to processing, withdraw consent or ask for a human review of a decision where applicable. Tell us which account or request is involved; we may need proportionate proof of identity before disclosing or changing records.`,
    'These rights may be subject to lawful limits. We will explain any restriction or retention obligation and respond within the applicable legal timeframe. You may complain directly to the Nigeria Data Protection Commission or seek other available remedies without first completing our internal complaint process.',
  ] },
  { title: 'Security, children and updates', paragraphs: [
    'We use measures appropriate to the service and information involved, but no website or transmission method is risk free. Report suspected exposure or unauthorised access through Contact Us. Do not include passwords, OTPs or sensitive documents in that report.',
    'Naitrust is intended for adults aged 18 and over and authorised business representatives. Contact us if a child’s information has been submitted so we can review and remove it where appropriate.',
    'We will update this notice when our practices change and bring material changes to your attention. A revised notice does not substitute for fresh consent where consent is required. Planned collection will be explained again at the point of use.',
  ] },
];

export const termsSections: PolicySection[] = [
  { title: 'Service and operator', paragraphs: [service.description, `These terms cover the website, early access list and invited product preview operated by ${service.company}. Live payment services will require the service-specific terms and provider disclosures presented before use.`] },
  { title: 'Eligibility and accounts', paragraphs: ['You must be at least 18, provide accurate information, have authority to act for any business you represent and keep your credentials private. Joining early access is free and does not guarantee an account, approval or a launch date. Invited test access uses fictional balances and payment activity. No real money is involved.'] },
  { title: 'Protected Deals and payment responsibilities', paragraphs: [
    'The proposed workflow lets parties agree the goods or services, amount, deadline, evidence and release conditions, complete required checks, fund through an approved provider and review delivery or performance. Release may follow an accepted approval or review deadline only under the applicable provider arrangement and risk controls.',
    service.paymentBoundary,
    'Naitrust is not a bank, deposit taking institution, insurer, licensed escrow trustee or guarantor. We do not promise an unconditional refund, delivery, product quality or payment recovery. Participants remain responsible for lawful transactions, genuine evidence and accurate terms. Verification records specified checks at a point in time.',
  ] },
  { title: 'Fees, subscriptions and taxes', paragraphs: [
    service.fees,
    'Launch pricing is not final. A live quote must show the amount for goods or services, each applicable fee, taxes where applicable, total payable, fee payer and any deduction from the recipient’s amount. Accepting one fee does not authorise undisclosed additional charges.',
    'If subscriptions are introduced, the price, included features, billing interval, renewal method and cancellation terms will be shown before enrolment. No paid subscription or automatic renewal is created by joining early access or choosing a preview preference. See Fees and pricing for details.',
  ] },
  { title: 'Cancellations, refunds and complaints', paragraphs: [
    'Live cancellation and refund eligibility will depend on the service, accepted terms, payment stage, evidence, applicable law and provider rules. Do not assume that a disputed payment has been frozen until the status confirms it. Reporting an issue does not automatically pause payment. Include supporting evidence and check the payment status for confirmation.',
    'Report a problem promptly through the Deal Room when available, Contact Us or Report a Concern. Include the reference and relevant evidence. A release deadline does not remove statutory consumer rights, warranty rights, fraud reporting or other legal remedies. Read the Refund and cancellation policy and Complaints process for details.',
  ] },
  { title: 'Acceptable use and fraud prevention', paragraphs: ['Do not use Naitrust for illegal goods or services, money laundering, terrorist financing, sanctions evasion, fraud, impersonation, stolen payment details, false evidence, unauthorised access or attempts to bypass checks. We may restrict access to investigate misuse, comply with legal obligations or protect users. A restriction does not automatically determine ownership of disputed funds or remove available rights of review.'] },
  { title: 'Optional legal review', paragraphs: [
    'Legal review is a planned, separately priced service. The named reviewer’s scope and agreement must be accepted by both parties. It is not included automatically in a Protected Deal.',
    ...legalTermsSections.map(section => section.body),
    'Naitrust is not a law firm. A reviewer’s professional responsibilities and engagement terms must be identified before a live appointment.',
  ] },
  { title: 'Privacy and communications', paragraphs: ['Our Privacy Policy describes the information collected, uses, sharing and choices for the website and preview, as well as planned collection at launch. Optional marketing consent is separate from agreement to service terms. You may contact us about privacy or unsubscribe from optional updates.'] },
  { title: 'Content, availability and responsibility', paragraphs: [
    'You retain rights in your content and authorise its use and sharing only as needed for the service you request, including the agreed Deal Room access. You must have permission to upload it. Naitrust’s branding, software and original content belong to Naitrust or its licensors.',
    'We aim to provide accurate information and reliable access, but cannot promise uninterrupted service or the conduct of another participant. Nothing here excludes obligations or liabilities that cannot lawfully be excluded, or removes statutory consumer or data protection rights.',
  ] },
  { title: 'Changes, governing law and contact', paragraphs: [`These terms are governed by Nigerian law. Material changes and new live service terms will be presented before they apply. Questions and complaints can be sent to ${service.contact}. Internal review does not prevent you from approaching a competent regulator, seeking independent advice or using available legal remedies.`] },
];

export const complianceSections: PolicySection[] = [
  { title: 'What Naitrust offers', paragraphs: [service.description, 'The current focus is Nigerian individuals and businesses making purchases, service payments, deposits and commercial payments. Cross border transfers, foreign exchange, lending and other financial services are not currently offered on this website.'] },
  { title: 'How payments are handled', paragraphs: [service.paymentBoundary, 'Payment provider details and the terms that apply to your deal will be shown before you pay.', 'Test payment events and account balances are simulations. Do not transfer real money to an account displayed in a demonstration.'] },
  { title: 'Identity, businesses and beneficiaries', paragraphs: ['Planned checks may include identity, contact details, business registration, beneficial ownership, representative authority and the intended payment recipient. Requirements depend on the transaction, risk and provider. A failed or incomplete check may require more information or manual review.', 'A verification badge records particular checks at a point in time. It does not certify every claim, title document, product, service or future action. See the Verification Policy for scope, privacy and review options.'] },
  { title: 'Financial crime and prohibited activity', paragraphs: ['Naitrust does not permit fraud, money laundering, terrorist financing, sanctions evasion, illegal goods or services, impersonation, deceptive evidence or attempts to bypass controls. These restrictions apply to individuals, businesses and representatives.', 'We may request additional information or restrict a transaction to investigate suspicious activity or meet legal requirements. We may be unable to disclose details of a review where the law prohibits it.'] },
  { title: 'Release, refunds and fair review', paragraphs: ['A live payment must have accepted release conditions, a clearly disclosed review period and provider confirmed status. A screen label alone is not proof that funds have moved. Required risk controls and unresolved evidence backed disputes must be considered before release.', 'Complaints should include the transaction reference, issue and available evidence. Both parties should have an opportunity to respond. Refund eligibility and timing depend on the facts and applicable provider rules; no outcome is guaranteed. Consumer rights continue after a payment review deadline.'] },
  { title: 'Privacy and security', paragraphs: ['Our Privacy Policy explains current collection and planned use of identity, business and payment information. Deal specific liveness and document sharing require clear notices. Restricting participant access and deleting underlying records are separate actions.', 'Access to deal information is limited to authorised participants and the people needed to provide support or review an issue.'] },
  { title: 'Contact and escalation', paragraphs: [`Send service, compliance and privacy questions to ${service.contact} or use Contact Us. Use Report a Concern for suspected fraud or misuse. Our Complaints process explains how to request further review and access external channels.`] },
];

export const pricingSections: PolicySection[] = [
  { title: 'Joining the waiting list', paragraphs: ['Joining is free. It does not create a subscription or authorise a charge. Payment services are not yet open to the public.'] },
  { title: 'Before you pay', paragraphs: [service.fees, 'Your payment summary will show the amount for goods or services, any Naitrust or provider fees, applicable taxes and the total payable. It will also explain who pays each charge and what the recipient receives.'] },
  { title: 'Optional services', paragraphs: ['You choose whether to use an optional paid service. Its price and terms will be shown before you agree. If subscriptions become available, the billing, renewal and cancellation terms will be explained before you subscribe.'] },
  { title: 'Questions about a charge', paragraphs: [`Contact ${service.contact} if a charge is unclear. For an incorrect or duplicate charge, include the payment reference, date and amount. Do not send passwords, verification codes or full card details. See Refunds and Complaints for help.`] },
];

export const refundSections: PolicySection[] = [
  { title: 'Current availability', paragraphs: ['Early access registration is free and creates no paid subscription. Preview payments are simulated and cannot be withdrawn or refunded as real money. Live refund processing is not yet publicly available.', 'This page explains the intended process. Service specific refund conditions and provider information must be presented before a live purchase or payment.'] },
  { title: 'Cancelling a deal or service', paragraphs: ['Before funding, follow the available cancellation or withdrawal process and notify the other party. After funding, cancellation is a request, not proof of reversal. Eligibility may depend on work already performed, accepted terms, evidence, statutory rights and the payment provider.', 'A subscription cancellation stops future renewal under the plan terms; it does not necessarily reverse a completed charge or cancel a separate Protected Deal.'] },
  { title: 'Requesting a refund', paragraphs: [`Use the Deal Room when available, Contact Us or ${service.contact}. Provide the deal or payment reference, date, amount, reason and relevant evidence. Examples include a duplicate charge, incorrect amount, non-delivery, a materially different item or an unprovided service. Do not share passwords, OTPs, PINs or full card details.`, 'We will review the request, seek relevant information from the parties or provider and communicate the outcome and reasons. Keep your reference when requesting an update or further review.'] },
  { title: 'Amounts, fees and processing', paragraphs: ['An approved refund may be full or partial depending on the facts, agreement and applicable law. Treatment of platform, payment provider or optional service fees must be disclosed before purchase; this page does not declare all fees non refundable.', 'Approved live refunds will follow the relevant provider process and ordinarily return through the original payment method, subject to provider and legal requirements. Provider processing or investigations may affect timing. A request or approval is not confirmation that money has reached your account. No fixed refund time is promised before provider terms are available.'] },
  { title: 'Disputes and consumer rights', paragraphs: ['Report issues promptly and preserve relevant evidence. Reporting alone does not automatically freeze payment in the planned workflow; relevant evidence or an applicable risk control is required. Do not assume a freeze until the status confirms it.', 'A delivery review window, payment release or internal decision does not remove applicable statutory, warranty, fraud reporting or other legal rights. You may request further review through Complaints or approach your payment provider, an appropriate regulator or a competent court.'] },
];

export const complaintsSections: PolicySection[] = [
  { title: 'How to complain', paragraphs: [`Use Contact Us or email ${service.contact} with “Complaint” and a short description in the subject. Use Report a Concern for suspected fraud, impersonation or misuse. Privacy requests and complaints can use the same contact with “Privacy” in the subject. You do not need a paid account to raise a complaint.`, 'Include your contact details, any deal or payment reference, what happened, when it happened, relevant evidence and the outcome you are requesting. Never include passwords, OTPs, transaction PINs or full payment card details.'] },
  { title: 'What happens next', paragraphs: ['We review the complaint, request any necessary information and route it to the responsible team or applicable provider. Keep any submission confirmation and reference for follow up. A form error is not confirmation that a complaint was received; use email if submission fails.', 'We will communicate the outcome and reasons, or explain what remains under review. Timing depends on complexity, required evidence and provider involvement, subject to applicable legal requirements. We do not promise immediate fund recovery or a fixed resolution time.'] },
  { title: 'Requesting further review', paragraphs: ['If you disagree with an outcome, reply with the reference, the reason you disagree and any additional evidence, and request further review. Payment provider issues may also need to be raised through that provider’s complaint process; provider details will be disclosed for live transactions.', 'An urgent safety, suspected account takeover or privacy issue should be clearly marked so it can be triaged. Contact your bank or payment provider promptly about an unauthorised real payment.'] },
  { title: 'External rights and escalation', paragraphs: ['You may approach the Nigeria Data Protection Commission for privacy matters. For consumer complaints, the Federal Competition and Consumer Protection Commission asks that you first raise the matter with the provider and keep the supporting records; if unresolved, follow its complaint process. You may also seek independent advice and use available legal remedies. Our internal process does not remove these rights or require you to waive them.', 'Live payment complaints may also fall under the relevant provider’s regulatory framework. The applicable provider and escalation channels will be identified when those services launch.'] },
];
